require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LunchplansController do

  # This should return the minimal set of attributes required to create a valid
  # Lunchplan. As you add validations to Lunchplan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "day" => "2013-01-24" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LunchplansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lunchplans as @lunchplans" do
      lunchplan = Lunchplan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lunchplans).should eq([lunchplan])
    end
  end

  describe "GET show" do
    it "assigns the requested lunchplan as @lunchplan" do
      lunchplan = Lunchplan.create! valid_attributes
      get :show, {:id => lunchplan.to_param}, valid_session
      assigns(:lunchplan).should eq(lunchplan)
    end
  end

  describe "GET new" do
    it "assigns a new lunchplan as @lunchplan" do
      get :new, {}, valid_session
      assigns(:lunchplan).should be_a_new(Lunchplan)
    end
  end

  describe "GET edit" do
    it "assigns the requested lunchplan as @lunchplan" do
      lunchplan = Lunchplan.create! valid_attributes
      get :edit, {:id => lunchplan.to_param}, valid_session
      assigns(:lunchplan).should eq(lunchplan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lunchplan" do
        expect {
          post :create, {:lunchplan => valid_attributes}, valid_session
        }.to change(Lunchplan, :count).by(1)
      end

      it "assigns a newly created lunchplan as @lunchplan" do
        post :create, {:lunchplan => valid_attributes}, valid_session
        assigns(:lunchplan).should be_a(Lunchplan)
        assigns(:lunchplan).should be_persisted
      end

      it "redirects to the created lunchplan" do
        post :create, {:lunchplan => valid_attributes}, valid_session
        response.should redirect_to(Lunchplan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lunchplan as @lunchplan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lunchplan.any_instance.stub(:save).and_return(false)
        post :create, {:lunchplan => { "day" => "invalid value" }}, valid_session
        assigns(:lunchplan).should be_a_new(Lunchplan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lunchplan.any_instance.stub(:save).and_return(false)
        post :create, {:lunchplan => { "day" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lunchplan" do
        lunchplan = Lunchplan.create! valid_attributes
        # Assuming there are no other lunchplans in the database, this
        # specifies that the Lunchplan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lunchplan.any_instance.should_receive(:update_attributes).with({ "day" => "2013-01-24" })
        put :update, {:id => lunchplan.to_param, :lunchplan => { "day" => "2013-01-24" }}, valid_session
      end

      it "assigns the requested lunchplan as @lunchplan" do
        lunchplan = Lunchplan.create! valid_attributes
        put :update, {:id => lunchplan.to_param, :lunchplan => valid_attributes}, valid_session
        assigns(:lunchplan).should eq(lunchplan)
      end

      it "redirects to the lunchplan" do
        lunchplan = Lunchplan.create! valid_attributes
        put :update, {:id => lunchplan.to_param, :lunchplan => valid_attributes}, valid_session
        response.should redirect_to(lunchplan)
      end
    end

    describe "with invalid params" do
      it "assigns the lunchplan as @lunchplan" do
        lunchplan = Lunchplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lunchplan.any_instance.stub(:save).and_return(false)
        put :update, {:id => lunchplan.to_param, :lunchplan => { "day" => "invalid value" }}, valid_session
        assigns(:lunchplan).should eq(lunchplan)
      end

      it "re-renders the 'edit' template" do
        lunchplan = Lunchplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lunchplan.any_instance.stub(:save).and_return(false)
        put :update, {:id => lunchplan.to_param, :lunchplan => { "day" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lunchplan" do
      lunchplan = Lunchplan.create! valid_attributes
      expect {
        delete :destroy, {:id => lunchplan.to_param}, valid_session
      }.to change(Lunchplan, :count).by(-1)
    end

    it "redirects to the lunchplans list" do
      lunchplan = Lunchplan.create! valid_attributes
      delete :destroy, {:id => lunchplan.to_param}, valid_session
      response.should redirect_to(lunchplans_url)
    end
  end

end
